module.exports = {
    none_to_delete: '删除对象不存在',
    none_to_operate: '数据不存在',
    grab_unavailable: '请先完成当前订单',
    driver_unavailable: '该司机正在运输，不能接受新订单',
    vehicle_num_occupied: '车牌号已存在',
    phone_occupied: '手机号已被占用',
    vehicle_processing: '车辆当前有运输任务，不可修改',
    driver_busy: '司机正在执行任务',
    user_disabled: '用户不存在,请重新绑定或联系车队登记',
    weChat_unbind: '该用户未绑定微信账户',
    order_occupied: '该订单已被接单',
    level_mismatch: '该订单已失效',//类别不匹配时
    cus_fac_exists: '该客户工厂已存在',
    cus_fac_short_exists: '该客户工厂简称已存在',
    common_api_01: '已经存在',
    common_api_02: '选定项目不存在',
    eirless_01: '无纸化接口调用失败',
    eirless_02: '无纸化业务单号错误',
    eirless_03: '该SO号不存在已办业务',
    gps_failed: 'GPS定位失败，请行驶至开阔处或打开手机GPS功能后再次尝试',
    so_code_duplicated: '该SO号已发单，不可重复发单',
    api_template_01: '模板不存在',
    late_for_process: '操作失败，该订单已开始运输',
    domain_01: '组织已存在',
    domain_02: '机构不存在',
    group_01: '用户组已存在',
    group_02: '用户组不存在',
    group_03: '叶子节点没有路径',
    group_04: '用户组下存在用户',
    user_01: '密码错误',
    user_02: '账号输入有误或不存在，请确认后重试',
    operator_01: '组不存在',
    operator_02: '用户已经存在',
    operator_03: '用户不存在',
    operator_04: '用户下有未完成订单',
    customer_01: '客户组不存在',
    customer_02: '客户已经存在',
    customer_03: '客户不存在',
    customer_04: '手机号已存在',
    menu_01: '菜单已经存在',
    menu_02: '菜单不存在',
    menu_03: '菜单下有子项',
    menu_04: '未配置路径',
    mbap_01: 'domain_id is missing',
    reg_01: 'phone is missing',
    reg_02: 'type is missing',
    reg_03: 'code is missing',
    reg_04: 'password is missing',
    reg_05: 'name is missing',
    auth_01: 'domain is missing',
    auth_02: 'parameter is missing',
    auth_03: 'identifyCode is missing',
    auth_04: 'magicNo is missing',
    auth_05: 'User does not exist or password is incorrect ',
    auth_06: '电话不存在',
    auth_07: '类型不存在',
    auth_08: '发送验证码失败',
    auth_09: '验证码错误',
    auth_10: '用户组不存在',
    auth_11: '用户类型不存在',
    auth_12: '验证码错误',
    auth_13: '请输入正确的手机号码',
    auth_14: '请输入正确的用户类型',
    auth_15: 'type is missing',
    auth_16: 'phone is missing',
    auth_17: 'code is missing',
    auth_18: 'password is missing',
    login_expired: 'Login has expired, please login again',
    emil_exist: 'the email has been used',
    username_exist: 'the username has been used',
    pwd_error: 'password is not right!',
    common_01: 'Method does not exist',
};
